-- AUTO-GENERATED by scripts/update-sounds.sh -- do not edit by hand.
local ADDON_NAME, ns = ...

ns.RegisterVoicePack("vivian", "Vivian", {
	{ name = "Adds", file = "adds.mp3" },
	{ name = "Countdown", file = "countdown.mp3" },
	{ name = "Danger", file = "danger.mp3" },
	{ name = "Kick", file = "kick.mp3" },
	{ name = "Magi", file = "magi.mp3" },
	{ name = "Move", file = "move.mp3" },
	{ name = "Note", file = "note.mp3" },
	{ name = "Run", file = "run.mp3" },
	{ name = "Soul", file = "soul.mp3" },
	{ name = "Spread", file = "spread.mp3" },
	{ name = "Stop", file = "stop.mp3" },
	{ name = "Surge", file = "surge.mp3" },
	{ name = "Warning", file = "warning.mp3" },
})
