#!/usr/bin/env bash
# Converts wav -> mp3, regenerates each voice pack's <Dir>/<PackLabel>.lua registration
# table from the mp3 files present, and keeps the auto-generated block in cfm_voice.toc
# in sync. Safe to re-run any time; output is deterministic.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

TOC_FILE="cfm_voice.toc"
BEGIN_MARKER="# BEGIN AUTO-GENERATED VOICE PACKS (scripts/update-sounds.sh)"
END_MARKER="# END AUTO-GENERATED VOICE PACKS"

title_case() {
	# "raid_wipe" / "raid-wipe" -> "Raid Wipe"
	printf '%s' "$1" | tr '_-' '  ' | awk '{ for (i = 1; i <= NF; i++) $i = toupper(substr($i,1,1)) substr($i,2); print }'
}

pack_label() {
	# "vivian" -> "Vivian"
	printf '%s' "$1" | awk '{ print toupper(substr($0,1,1)) substr($0,2) }'
}

echo "Converting audio (make convert)..."
make convert

echo "Discovering voice pack directories..."
pack_dirs=()
for entry in */; do
	dir="${entry%/}"
	case "$dir" in
		.git|hooks|scripts|.*) continue ;;
	esac
	if ls "$dir"/*.mp3 >/dev/null 2>&1; then
		pack_dirs+=("$dir")
	fi
done

if [ "${#pack_dirs[@]}" -eq 0 ]; then
	echo "No voice pack directories found (looked for top-level dirs containing *.mp3)."
	exit 0
fi

IFS=$'\n' pack_dirs=($(printf '%s\n' "${pack_dirs[@]}" | sort)); unset IFS

toc_lines=()

for dir in "${pack_dirs[@]}"; do
	label="$(pack_label "$dir")"
	lua_file="$dir/$label.lua"

	mp3_files=()
	for f in "$dir"/*.mp3; do
		mp3_files+=("$(basename "$f")")
	done
	IFS=$'\n' mp3_files=($(printf '%s\n' "${mp3_files[@]}" | sort)); unset IFS

	{
		echo "-- AUTO-GENERATED by scripts/update-sounds.sh -- do not edit by hand."
		echo "local ADDON_NAME, ns = ..."
		echo ""
		echo "ns.RegisterVoicePack(\"$dir\", \"$label\", {"
		for f in "${mp3_files[@]}"; do
			stem="${f%.mp3}"
			name="$(title_case "$stem")"
			printf '\t{ name = "%s", file = "%s" },\n' "$name" "$f"
		done
		echo "})"
	} > "$lua_file"

	echo "✓ Wrote $lua_file (${#mp3_files[@]} sound(s))"

	toc_lines+=("$dir\\$label.lua")
done

if grep -qF "$BEGIN_MARKER" "$TOC_FILE"; then
	lines_file="$(mktemp)"
	printf '%s\n' "${toc_lines[@]}" > "$lines_file"
	# Replacement lines are read from a file via getline rather than passed through
	# awk -v, since -v runs backslash-escape processing on its value and would mangle
	# the "dir\Label.lua" backslashes in toc_lines.
	awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v linesfile="$lines_file" '
		$0 == begin {
			print
			while ((getline l < linesfile) > 0) print l
			close(linesfile)
			skip = 1
			next
		}
		$0 == end { skip = 0 }
		skip { next }
		{ print }
	' "$TOC_FILE" > "$TOC_FILE.tmp"
	mv "$TOC_FILE.tmp" "$TOC_FILE"
	rm -f "$lines_file"
else
	{
		echo ""
		echo "$BEGIN_MARKER"
		printf '%s\n' "${toc_lines[@]}"
		echo "$END_MARKER"
	} >> "$TOC_FILE"
fi

echo "✓ Updated $TOC_FILE with ${#pack_dirs[@]} voice pack(s)"
